import { Repository } from '@/types/github';

// Mock data for repositories
export const mockRepositories: Repository[] = [
  {
    id: 1,
    name: 'screeps-world-mcp',
    full_name: 'admon84/screeps-world-mcp',
    description:
      'Experimental mcp (model context protocol) service for screeps world.',
    html_url: 'https://github.com/admon84/screeps-world-mcp',
    homepage: '',
    language: 'TypeScript',
    topics: ['nodejs', 'typescript', 'ai', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 2,
    name: 'screeps-room-planner',
    full_name: 'admon84/screeps-room-planner',
    description: 'Screeps room planner react app.',
    html_url: 'https://github.com/admon84/screeps-room-planner',
    homepage: 'https://screeps-room-planner.vercel.app',
    language: 'TypeScript',
    topics: ['nodejs', 'react', 'nextjs', 'typescript', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 3,
    name: 'screeps-world-openapi',
    full_name: 'screepers/screeps-world-openapi',
    description: 'Openapi spec for screeps world web api.',
    html_url: 'https://github.com/screepers/screeps-world-openapi',
    homepage: 'https://screepers.github.io/screeps-world-openapi/',
    language: 'openapi',
    topics: ['openapi', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 4,
    name: 'screeps-autonomous-framework',
    full_name: 'admon84/screeps-autonomous-framework',
    description: 'Screeps world starter kit and base bot.',
    html_url: 'https://github.com/admon84/screeps-autonomous-framework',
    homepage: '',
    language: 'TypeScript',
    topics: ['typescript', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 5,
    name: 'screeps-arena-typescript-sample-bot',
    full_name: 'admon84/screeps-arena-typescript-sample-bot',
    description: 'Screeps arena starter kit and base bot.',
    html_url: 'https://github.com/admon84/screeps-arena-typescript-sample-bot',
    homepage: '',
    language: 'TypeScript',
    topics: ['typescript', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 6,
    name: 'screepsmod-decorate',
    full_name: 'admon84/screepsmod-decorate',
    description: 'Screeps mod for room decorations.',
    html_url: 'https://github.com/admon84/screepsmod-decorate',
    homepage: '',
    language: 'TypeScript',
    topics: ['typescript', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 7,
    name: 'screeps-map-downloader',
    full_name: 'admon84/screeps-map-downloader',
    description: 'Screeps map downloader cli tool.',
    html_url: 'https://github.com/admon84/screeps-map-downloader',
    homepage: '',
    language: 'Python',
    topics: ['python', 'cli', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 8,
    name: 'python-screeps-spybot',
    full_name: 'admon84/python-screeps-spybot',
    description: 'Experimental spy tool for screeps.',
    html_url: 'https://github.com/admon84/python-screeps-spybot',
    homepage: '',
    language: 'Python',
    topics: ['python', 'cli', 'screeps'],
    archived: false,
    fork: false,
  },
  {
    id: 9,
    name: 'CrosshairOverlay',
    full_name: 'admon84/CrosshairOverlay',
    description: 'Gaming crosshair overlay.',
    html_url: 'https://github.com/admon84/CrosshairOverlay',
    homepage: '',
    language: 'C#',
    topics: ['windows', 'csharp', 'dotnet'],
    archived: false,
    fork: false,
  },
];

// Simple function to get repositories
export const getRepositories = (): Repository[] => {
  return mockRepositories;
};
